import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Isso é Meta Tag',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <nav>
        <h4>Navegação</h4>
          <ul>
            <li><Link href="/">Início</Link></li>
            <li><Link href="/pages/Home">Home</Link></li>
            <li><Link href="/pages/AboutUs">Sobre Nós</Link></li>
            <li><Link href="/pages/Login">Login</Link></li>
          </ul>
      </nav>
      <body className={inter.className}>
        {children}  
      </body>
    </html>
  )
}
